networks:
  swag:
    external: true

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    networks:
      - swag
    container_name: drigax_com
    expose: 
      - '80'
      - '443'
    labels:
      - 'swag=enable'
      - 'swag_address=site'
      - 'swag_url=site.drigax.com'
      - 'swag_proto=http'
      - 'swag_port=80'
    
    
